
RUN dpkg --add-architecture i386 && apt-get update
# && apt-get -y install libc-bin gcc-multilib
# Use `ldd /usr/bin/snx.800010003` for check list of dynamically linked library

ADD dist/snx-800008209_800008209-2_amd64.deb /tmp/
ADD dist/snx-800008304_800008304-2_amd64.deb /tmp/
ADD dist/snx-800010003_800010003-2_amd64.deb /tmp/

# Check install
RUN apt-get -y install /tmp/snx-800008209_800008209-2_amd64.deb
RUN apt-get -y install /tmp/snx-800008304_800008304-2_amd64.deb
RUN apt-get -y install /tmp/snx-800010003_800010003-2_amd64.deb

# Use: docker build --build-arg BUILD_TIMESTAMP=$(date -uIs)
ARG BUILD_TIMESTAMP
LABEL BUILD_TIMESTAMP="$BUILD_TIMESTAMP"

# Verify
RUN echo -e "\n\nVerify:"; \
    cat /etc/os-release; \
    echo -e "\nWhich 'snx': $(which snx)"; \
    echo -e "\nList binaries: "; ls -la /usr/bin/snx* /usr/local/bin/snx* /etc/alternatives/snx; \
    echo -e "\nAlternatives: "; update-alternatives --display snx; \
    echo -e "\nUsage:"; snx usage

# Check uninstall
RUN apt-get -y remove snx-800010003
RUN apt-get -y remove snx-800008304
RUN apt-get -y remove snx-800008209
