FROM debian:bookworm-slim

# Use: docker build --build-arg BUILD_TIMESTAMP=$(date -uIs)
ARG BUILD_TIMESTAMP
LABEL BUILD_TIMESTAMP="$BUILD_TIMESTAMP"

ENV DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture i386 && apt-get update
# && apt-get install -y libc-bin gcc-multilib
# Use `ldd /usr/bin/snx.800008407` for check list of dynamically linked library

COPY --link dist/snx-*_amd64.deb /dist/

# Check install
RUN apt-get install -y --no-install-recommends /dist/snx-800008209_800008209-2_amd64.deb
RUN apt-get install -y --no-install-recommends /dist/snx-800008304_800008304-2_amd64.deb
RUN apt-get install -y --no-install-recommends /dist/snx-800008407_800008407-2_amd64.deb
RUN apt-get install -y --no-install-recommends /dist/snx-800010003_800010003-2_amd64.deb

# Verify all
RUN echo -e "\n\nVerify all:"; \
    cat /etc/os-release | grep -v _URL; \
    echo -e "\nWhich 'snx': $(which snx)"; \
    echo -e "\nList binaries: "; ls -la /usr/bin/snx* /usr/local/bin/snx* /etc/alternatives/snx; \
    echo -e "\nAlternatives: "; update-alternatives --display snx; \
    echo -e "\nCheck 'snx':"; snx -h

# Verify each
RUN echo -e "\n\nVerify each version:" && \
    echo -e "\nCheck '/usr/bin/snx.800008209':"; /usr/bin/snx.800008209 -h
RUN echo -e "\nCheck '/usr/bin/snx.800008304':"; /usr/bin/snx.800008304 -h
RUN echo -e "\nCheck '/usr/bin/snx.800008407':"; /usr/bin/snx.800008407 -h
RUN echo -e "\nCheck '/usr/bin/snx.800010003':"; /usr/bin/snx.800010003 -h

# Check uninstall
RUN apt-get remove -y snx-800010003
RUN apt-get remove -y snx-800008407
RUN apt-get remove -y snx-800008304
RUN apt-get remove -y snx-800008209
RUN apt-get autoremove -y; \
    rm -rf /var/lib/apt/lists/*
